// src/app/components/ionic-selectable/ionic-selectable-modal.component.ts
import { AfterViewInit, Component, ElementRef, HostBinding, ViewChild } from '@angular/core';
import { Content, NavParams, Searchbar } from 'ionic-angular';
import { IonicSelectableComponent } from './ionic-selectable.component';

@Component({
  selector: 'ionic-selectable-modal',
  templateUrl: './ionic-selectable-modal.component.html'
})
export class IonicSelectableModalComponent implements AfterViewInit {
  @HostBinding('class.ionic-selectable-modal')
  private _cssClass = true;
  @HostBinding('class.ionic-selectable-modal-can-clear')
  private get _canClearCssClass(): boolean {
    return this.selectComponent.canClear;
  }
  @HostBinding('class.ionic-selectable-modal-is-multiple')
  private get _isMultipleCssClass(): boolean {
    return this.selectComponent.isMultiple;
  }
  @HostBinding('class.ionic-selectable-modal-is-searching')
  private get _isSearchingCssClass(): boolean {
    return this.selectComponent._isSearching;
  }
  @HostBinding('class.ionic-selectable-modal-is-add-item-template-visible')
  private get _isAddItemTemplateVisibleCssClass(): boolean {
    return this.selectComponent._isAddItemTemplateVisible;
  }
  @HostBinding('class.ionic-selectable-modal-ios')
  private get _isIos(): boolean {
    return this.selectComponent._isIos;
  }
  @HostBinding('class.ionic-selectable-modal-md')
  private _isMD(): boolean {
    return this.selectComponent._isMD;
  }
  @ViewChild('searchbarComponent')
  _searchbarComponent: Searchbar;
  @ViewChild(Content)
  _content: Content;
  selectComponent: IonicSelectableComponent;
  _header: HTMLElement;

  constructor(
    private navParams: NavParams,
    public _element: ElementRef,
  ) {
    this.selectComponent = this.navParams.get('selectComponent');
    this.selectComponent._modalComponent = this;
    this.selectComponent._selectedItems = [];

    if (!this.selectComponent._isNullOrWhiteSpace(this.selectComponent.value)) {
      if (this.selectComponent.isMultiple) {
        this.selectComponent.value.forEach(item => {
          this.selectComponent._selectedItems.push(item);
        });
      } else {
        this.selectComponent._selectedItems.push(this.selectComponent.value);
      }
    }

    this.selectComponent._setItemsToConfirm(this.selectComponent._selectedItems);
  }

  ngAfterViewInit() {
    this._header = this._element.nativeElement.querySelector('ion-header');
    if (this._searchbarComponent && this.selectComponent.focusSearchbar) {
      // Focus after a delay because focus doesn't work without it.
      setTimeout(() => {
        this._searchbarComponent.setFocus();
      }, 1000);
    }
  }
}

<ion-header>
  <ion-toolbar *ngIf="!selectComponent.headerTemplate"
    [color]="selectComponent.headerColor ? selectComponent.headerColor : null">
    <ion-buttons [slot]="selectComponent.closeButtonSlot">
      <ion-button (click)="selectComponent._close()">
        <span *ngIf="selectComponent.closeButtonTemplate"
          [ngTemplateOutlet]="selectComponent.closeButtonTemplate">
        </span>
        <span *ngIf="!selectComponent.closeButtonTemplate">
          {{selectComponent.closeButtonText}}
        </span>
      </ion-button>
    </ion-buttons>
    <ion-title>
      <!-- Need span for for text ellipsis. -->
      <span *ngIf="selectComponent.titleTemplate"
        [ngTemplateOutlet]="selectComponent.titleTemplate">
      </span>
      <span *ngIf="!selectComponent.titleTemplate">
        {{selectComponent.label}}
      </span>
    </ion-title>
  </ion-toolbar>
  <div *ngIf="selectComponent.headerTemplate"
    [ngTemplateOutlet]="selectComponent.headerTemplate">
  </div>
  <ion-toolbar
    *ngIf="selectComponent.canSearch || selectComponent.messageTemplate">
    <ion-searchbar *ngIf="selectComponent.canSearch" #searchbarComponent
      [(ngModel)]="selectComponent._searchText"
      (ionChange)="selectComponent._filterItems()"
      (ionClear)="selectComponent._onSearchbarClear()"
      [placeholder]="selectComponent.searchPlaceholder"
      [debounce]="selectComponent.searchDebounce">
    </ion-searchbar>
    <div class="ionic-selectable-message"
      *ngIf="selectComponent.messageTemplate">
      <div [ngTemplateOutlet]="selectComponent.messageTemplate">
      </div>
    </div>
  </ion-toolbar>
</ion-header>
<ion-content>
  <div class="ionic-selectable-spinner" *ngIf="selectComponent._isSearching">
    <div class="ionic-selectable-spinner-background"></div>
    <ion-spinner></ion-spinner>
  </div>
  <ion-list class="ion-no-margin"
    *ngIf="!selectComponent.hasVirtualScroll && selectComponent._hasFilteredItems">
    <ion-item-group *ngFor="let group of selectComponent._filteredGroups"
      class="ionic-selectable-group">
      <ion-item-divider *ngIf="selectComponent._hasGroups"
        [color]="selectComponent.groupColor ? selectComponent.groupColor : null">
        <!-- Need span for for text ellipsis. -->
        <span *ngIf="selectComponent.groupTemplate"
          [ngTemplateOutlet]="selectComponent.groupTemplate"
          [ngTemplateOutletContext]="{ group: group }">
        </span>
        <!-- Need ion-label for text ellipsis. -->
        <ion-label *ngIf="!selectComponent.groupTemplate">
          {{group.text}}
        </ion-label>
        <div *ngIf="selectComponent.groupEndTemplate" slot="end">
          <div [ngTemplateOutlet]="selectComponent.groupEndTemplate"
            [ngTemplateOutletContext]="{ group: group }">
          </div>
        </div>
      </ion-item-divider>
      <ion-item button="true" detail="false" *ngFor="let item of group.items"
        (click)="selectComponent._select(item)" class="ionic-selectable-item"
        [ngClass]="{
          'ionic-selectable-item-is-selected': selectComponent._isItemSelected(item),
          'ionic-selectable-item-is-disabled': selectComponent._isItemDisabled(item)
        }" [disabled]="selectComponent._isItemDisabled(item)">
        <!-- Need span for text ellipsis. -->
        <span *ngIf="selectComponent.itemTemplate"
          [ngTemplateOutlet]="selectComponent.itemTemplate"
          [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
        </span>
        <!-- Need ion-label for text ellipsis. -->
        <ion-label *ngIf="!selectComponent.itemTemplate">
          {{selectComponent._formatItem(item)}}
        </ion-label>
        <div *ngIf="selectComponent.itemEndTemplate" slot="end">
          <div [ngTemplateOutlet]="selectComponent.itemEndTemplate"
            [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
          </div>
        </div>
        <span *ngIf="selectComponent.itemIconTemplate"
          [ngTemplateOutlet]="selectComponent.itemIconTemplate"
          [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
        </span>
        <ion-icon *ngIf="!selectComponent.itemIconTemplate"
          [name]="selectComponent._isItemSelected(item) ? 'checkmark-circle' : 'radio-button-off'"
          [color]="selectComponent._isItemSelected(item) ? 'primary' : null"
          [slot]="selectComponent.itemIconSlot">
        </ion-icon>
        <ion-button *ngIf="selectComponent.canSaveItem"
          class="ionic-selectable-item-button" slot="end" fill="outline"
          (click)="selectComponent._saveItem($event, item)">
          <ion-icon slot="icon-only" ios="create" md="create-sharp"></ion-icon>
        </ion-button>
        <ion-button *ngIf="selectComponent.canDeleteItem"
          class="ionic-selectable-item-button" slot="end" fill="outline"
          (click)="selectComponent._deleteItemClick($event, item)">
          <ion-icon slot="icon-only" ios="trash" md="trash-sharp"></ion-icon>
        </ion-button>
      </ion-item>
    </ion-item-group>
  </ion-list>
  <!-- Fail text should be above InfiniteScroll to avoid a gap when no items are found. -->
  <div *ngIf="!selectComponent._hasFilteredItems">
    <span *ngIf="selectComponent.searchFailTemplate"
      [ngTemplateOutlet]="selectComponent.searchFailTemplate">
    </span>
    <div *ngIf="!selectComponent.searchFailTemplate" class="ion-margin">
      {{selectComponent.searchFailText}}
    </div>
  </div>
  <ion-infinite-scroll *ngIf="!selectComponent.hasVirtualScroll"
    [disabled]="!selectComponent.hasInfiniteScroll"
    (ionInfinite)="selectComponent._getMoreItems()">
    <ion-infinite-scroll-content></ion-infinite-scroll-content>
  </ion-infinite-scroll>
  <ion-virtual-scroll class="ion-no-margin"
    *ngIf="selectComponent.hasVirtualScroll && selectComponent._hasFilteredItems"
    [items]="selectComponent._filteredGroups[0].items"
    [headerFn]="selectComponent.virtualScrollHeaderFn"
    [approxItemHeight]="selectComponent.virtualScrollApproxItemHeight">
    <ion-item-divider *virtualHeader="let header"
      [color]="selectComponent.groupColor ? selectComponent.groupColor : null">
      {{header}}
    </ion-item-divider>
    <ion-item button="true" detail="false" *virtualItem="let item"
      (click)="selectComponent._select(item)" class="ionic-selectable-item"
      [ngClass]="{
        'ionic-selectable-item-is-selected': selectComponent._isItemSelected(item),
        'ionic-selectable-item-is-disabled': selectComponent._isItemDisabled(item)
      }" [disabled]="selectComponent._isItemDisabled(item)">
      <!-- Need span for text ellipsis. -->
      <span *ngIf="selectComponent.itemTemplate"
        [ngTemplateOutlet]="selectComponent.itemTemplate"
        [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
      </span>
      <!-- Need ion-label for text ellipsis. -->
      <ion-label *ngIf="!selectComponent.itemTemplate">
        {{selectComponent._formatItem(item)}}
      </ion-label>
      <div *ngIf="selectComponent.itemEndTemplate" slot="end">
        <div [ngTemplateOutlet]="selectComponent.itemEndTemplate"
          [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
        </div>
      </div>
      <span *ngIf="selectComponent.itemIconTemplate"
        [ngTemplateOutlet]="selectComponent.itemIconTemplate"
        [ngTemplateOutletContext]="{ item: item, isItemSelected: selectComponent._isItemSelected(item) }">
      </span>
      <ion-icon *ngIf="!selectComponent.itemIconTemplate"
        [name]="selectComponent._isItemSelected(item) ? 'checkmark-circle' : 'radio-button-off'"
        [color]="selectComponent._isItemSelected(item) ? 'primary' : null"
        [slot]="selectComponent.itemIconSlot">
      </ion-icon>
      <ion-button *ngIf="selectComponent.canSaveItem"
        class="ionic-selectable-item-button" slot="end" fill="outline"
        (click)="selectComponent._saveItem($event, item)">
        <ion-icon slot="icon-only" name="md-create"></ion-icon>
      </ion-button>
      <ion-button *ngIf="selectComponent.canDeleteItem"
        class="ionic-selectable-item-button" slot="end" fill="outline"
        (click)="selectComponent._deleteItemClick($event, item)">
        <ion-icon slot="icon-only" name="md-trash"></ion-icon>
      </ion-button>
    </ion-item>
  </ion-virtual-scroll>
</ion-content>
<div class="ionic-selectable-add-item-template"
  *ngIf="selectComponent._isAddItemTemplateVisible"
  [ngStyle]="{ 'top.px': _header.offsetHeight }">
  <div class="ionic-selectable-add-item-template-inner"
    [ngStyle]="{ 'height': selectComponent._addItemTemplateFooterHeight }">
    <span [ngTemplateOutlet]="selectComponent.addItemTemplate"
      [ngTemplateOutletContext]="{ item: selectComponent._itemToAdd, isAdd: selectComponent._itemToAdd === null }">
    </span>
  </div>
</div>
<ion-footer
  *ngIf="selectComponent._footerButtonsCount > 0 || selectComponent.footerTemplate"
  [ngStyle]="{ 'visibility': selectComponent._isFooterVisible ? 'initial' : 'hidden' }">
  <ion-toolbar *ngIf="!selectComponent.footerTemplate">
    <ion-row>
      <ion-col *ngIf="selectComponent.canClear">
        <ion-button expand="full" (click)="selectComponent._clear()"
          [disabled]="!selectComponent._selectedItems.length">
          {{selectComponent.clearButtonText}}
        </ion-button>
      </ion-col>
      <ion-col *ngIf="selectComponent.canAddItem">
        <ion-button expand="full" (click)="selectComponent._addItemClick()">
          {{selectComponent.addButtonText}}
        </ion-button>
      </ion-col>
      <ion-col
        *ngIf="selectComponent.isMultiple || selectComponent.hasConfirmButton">
        <ion-button expand="full" (click)="selectComponent._confirm()"
          [disabled]="!selectComponent.isConfirmButtonEnabled">
          {{selectComponent.confirmButtonText}}
        </ion-button>
      </ion-col>
    </ion-row>
  </ion-toolbar>
  <div *ngIf="selectComponent.footerTemplate"
    [ngTemplateOutlet]="selectComponent.footerTemplate">
  </div>
</ion-footer>

// packages/core/src/components/ionic-selectable-modal/ionic-selectable-modal.component.tsx
import { Component, h, Host, ComponentInterface, Method, State, Element } from '@stencil/core';
import { IonicSelectableComponent } from '../ionic-selectable/ionic-selectable.component';

/**
 * @internal
 */
@Component({
  tag: 'ionic-selectable-modal',
  styleUrls: {
    ios: 'ionic-selectable-modal.ios.component.scss',
    md: 'ionic-selectable-modal.md.component.scss',
  },
  scoped: true,
})
export class IonicSelectableModalComponent implements ComponentInterface {
  @Element() public element!: HTMLIonicSelectableModalElement;
  private selectableComponent: IonicSelectableComponent;
  private headerElement: HTMLIonHeaderElement;

  @State() private toggleUpdate: boolean = false;

  public infiniteScrollElement: HTMLIonInfiniteScrollElement;
  public virtualScrollElement: HTMLIonVirtualScrollElement;
  public contentElement: HTMLIonContentElement;
  /**
   * Rerender the component
   */
  @Method()
  public async update(): Promise<void> {
    this.toggleUpdate = !this.toggleUpdate;
  }

  public connectedCallback(): void {
    const modalElement = document.querySelector('ion-modal');
    this.selectableComponent = modalElement.componentProps.selectableComponent;
    this.selectableComponent.selectableModalComponent = this;
  }

  public componentDidLoad(): void {
    this.infiniteScrollElement = this.element.querySelector('ion-infinite-scroll');
    this.virtualScrollElement = this.element.querySelector('ion-virtual-scroll');
    this.contentElement = this.element.querySelector('ion-content');
    this.headerElement = this.element.querySelector('ion-header');
    if (this.selectableComponent.shouldFocusSearchbar) {
      const searchBarElement = this.element.querySelector('ion-searchbar');
      searchBarElement.setFocus();
      // Focus after a delay because focus doesn't work without it.
      setTimeout(() => {
        searchBarElement.setFocus();
      }, 1000);
    }
  }

  private renderItem(item: any): any {
    return (
      <ion-item
        button={true}
        onClick={(): void => this.selectableComponent.selectItem(item)}
        disabled={this.selectableComponent.isItemDisabled(item)}
      >
        {(!this.selectableComponent.hasTemplateRender || !this.selectableComponent.hasTemplateRender('item')) && (
          <ion-label>{this.selectableComponent.getItemText(item)}</ion-label>
        )}
        {this.selectableComponent.hasTemplateRender && this.selectableComponent.hasTemplateRender('item') && (
          <span
            ref={(element) => {
              this.selectableComponent.templateRender(element, {
                type: 'item',
                value: item,
                isItemSelected: this.selectableComponent.isItemSelected(item),
                isItemDisabled: this.selectableComponent.isItemDisabled(item),
              });
            }}
          ></span>
        )}
        <ion-icon
          name={this.selectableComponent.isItemSelected(item) ? 'checkmark-circle' : 'radio-button-off'}
          size="small"
          slot={this.selectableComponent.itemIconSlot}
        />
      </ion-item>
    );
  }

  private renderHeader(header: any): any {
    return (
      <ion-item-divider color={this.selectableComponent.groupColor}>
        {/* Need ion-label for text ellipsis. */}
        <ion-label>{header}</ion-label>
      </ion-item-divider>
    );
  }

  public render(): void {
    return (
      <Host
        class={{
          'ionic-selectable-modal-is-add-item-template-visible ': this.selectableComponent.isAddItemTemplateVisible,
        }}
      >
        <ion-header>
          <ion-toolbar color={this.selectableComponent.headerColor}>
            <ion-title>{this.selectableComponent.titleText}</ion-title>
            <ion-buttons slot={this.selectableComponent.closeButtonSlot}>
              <ion-button onClick={(): void => this.selectableComponent.closeModal()}>
                {this.selectableComponent.closeButtonText}
              </ion-button>
            </ion-buttons>
          </ion-toolbar>
          {this.selectableComponent.canSearch /* || selectComponent.messageTemplate */ && (
            <ion-toolbar>
              <ion-searchbar
                value={this.selectableComponent.searchText}
                placeholder={this.selectableComponent.searchPlaceholder}
                debounce={this.selectableComponent.searchDebounce}
                cancelButtonIcon={this.selectableComponent.searchCancelButtonIcon}
                cancelButtonText={this.selectableComponent.searchCancelButtonText}
                clearIcon={this.selectableComponent.searchClearIcon}
                inputmode={this.selectableComponent.searchInputmode}
                searchIcon={this.selectableComponent.searchIcon}
                showCancelButton={this.selectableComponent.searchShowCancelButton}
                onIonChange={(event): void => this.selectableComponent.onSearchbarValueChanged(event)}
              ></ion-searchbar>
            </ion-toolbar>
          )}
        </ion-header>
        <ion-content>
          {this.selectableComponent.isSearching && (
            <div class="ionic-selectable-spinner">
              <div class="ionic-selectable-spinner-background"></div>
              <ion-spinner></ion-spinner>
            </div>
          )}
          {!this.selectableComponent.hasFilteredItems && (
            <div class="ion-margin ion-text-center">{this.selectableComponent.searchFailText}</div>
          )}
          {!this.selectableComponent.hasVirtualScroll && this.selectableComponent.hasFilteredItems && (
            <ion-list>
              {this.selectableComponent.filteredGroups.map((group) => {
                return (
                  <ion-item-group>
                    {this.selectableComponent.hasGroups && (
                      <ion-item-divider color={this.selectableComponent.groupColor}>
                        {/* Need ion-label for text ellipsis. */}
                        <ion-label>{group.text}</ion-label>
                      </ion-item-divider>
                    )}
                    {group.items.map((item) => this.renderItem(item))}
                  </ion-item-group>
                );
              })}
            </ion-list>
          )}
          {this.selectableComponent.hasVirtualScroll && this.selectableComponent.hasFilteredItems && (
            <ion-virtual-scroll
              items={this.selectableComponent.filteredGroups[0].items}
              approxHeaderHeight={this.selectableComponent.virtualScrollApproxHeaderHeight}
              approxItemHeight={this.selectableComponent.virtualScrollApproxItemHeight}
              renderItem={(item): void => this.renderItem(item)}
              renderHeader={(header): void => this.renderHeader(header)}
              headerFn={this.selectableComponent.virtualScrollHeaderFn}
            ></ion-virtual-scroll>
          )}
          {this.selectableComponent.hasInfiniteScroll && (
            <ion-infinite-scroll
              threshold={this.selectableComponent.infiniteScrollThreshold}
              onIonInfinite={(): void => this.selectableComponent.getMoreItems()}
            >
              <ion-infinite-scroll-content></ion-infinite-scroll-content>
            </ion-infinite-scroll>
          )}
        </ion-content>
        {this.selectableComponent.isAddItemTemplateVisible && (
          <div
            class="ionic-selectable-add-item-template"
            style={{ top: this.headerElement.offsetHeight + 'px' }}
            ref={(element) => {
              this.selectableComponent.templateRender(element, {
                type: 'addItem',
                value: this.selectableComponent.itemToAdd,
                isAdd: this.selectableComponent.itemToAdd == null,
              });
            }}
          ></div>
        )}
        {this.selectableComponent.footerButtonsCount > 0 /* && selectComponent.footerTemplate */ && (
          <ion-footer style={{ visibility: this.selectableComponent.isFooterVisible ? 'initial' : 'hidden' }}>
            <ion-toolbar /* *ngIf="!selectComponent.footerTemplate" */>
              <ion-row>
                {this.selectableComponent.canClear && (
                  <ion-col>
                    <ion-button
                      onClick={(): void => this.selectableComponent.clearItems()}
                      disabled={!(this.selectableComponent.selectedItems.length > 0)}
                      expand="full"
                    >
                      {this.selectableComponent.clearButtonText}
                    </ion-button>
                  </ion-col>
                )}
                {this.selectableComponent.canAddItem && (
                  <ion-col>
                    <ion-button onClick={(): void => this.selectableComponent.addItemClick()} expand="full">
                      {this.selectableComponent.addButtonText}
                    </ion-button>
                  </ion-col>
                )}
                {(this.selectableComponent.isMultiple ||
                  this.selectableComponent.hasConfirmButton ||
                  this.selectableComponent.canClear) && (
                  <ion-col>
                    <ion-button
                      onClick={(): void => this.selectableComponent.confirmSelection()}
                      disabled={!this.selectableComponent.isConfirmButtonEnabled}
                      expand="full"
                    >
                      {this.selectableComponent.confirmButtonText}
                    </ion-button>
                  </ion-col>
                )}
              </ion-row>
            </ion-toolbar>
          </ion-footer>
        )}
      </Host>
    );
  }
}
